name: gym_stats_entry_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gym_icon.png"
  min_sdk_android: 21
